version: '4'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-i
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventory-service
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql